package com.chrisb97.warehouse.controller;
import com.chrisb97.warehouse.config.AppContext;import com.chrisb97.warehouse.model.*;import com.chrisb97.warehouse.util.AlertUtil;import javafx.beans.property.*;import javafx.collections.*;import javafx.fxml.FXML;import javafx.scene.control.*;import java.util.*;
public class ProductsController{
@FXML private TextField searchField,skuField,nameField,descriptionField,categoryField,minimumField;@FXML private ComboBox<String> categoryFilter;@FXML private ComboBox<Location> locationCombo;@FXML private CheckBox lowStockOnly,activeCheck;@FXML private TableView<Product> table;@FXML private TableColumn<Product,String> skuColumn,nameColumn,categoryColumn,quantityColumn,minimumColumn,locationColumn,statusColumn,activeColumn;private Product selected;
@FXML public void initialize(){skuColumn.setCellValueFactory(d->new SimpleStringProperty(d.getValue().getSku()));nameColumn.setCellValueFactory(d->new SimpleStringProperty(d.getValue().getName()));categoryColumn.setCellValueFactory(d->new SimpleStringProperty(d.getValue().getCategory()));quantityColumn.setCellValueFactory(d->new SimpleStringProperty(String.valueOf(d.getValue().getQuantity())));minimumColumn.setCellValueFactory(d->new SimpleStringProperty(String.valueOf(d.getValue().getMinimumStock())));locationColumn.setCellValueFactory(d->new SimpleStringProperty(d.getValue().getLocationCode()));statusColumn.setCellValueFactory(d->new SimpleStringProperty(d.getValue().getStockStatus()));activeColumn.setCellValueFactory(d->new SimpleStringProperty(d.getValue().isActive()?"Active":"Inactive"));table.getSelectionModel().selectedItemProperty().addListener((o,a,b)->edit(b));searchField.textProperty().addListener((o,a,b)->refresh());lowStockOnly.selectedProperty().addListener((o,a,b)->refresh());categoryFilter.valueProperty().addListener((o,a,b)->refresh());locationCombo.setItems(FXCollections.observableArrayList(AppContext.getInstance().locations().activeLocations()));List<Product> all=AppContext.getInstance().products().search("",null,false);Set<String> categories=new TreeSet<>();all.forEach(p->{if(p.getCategory()!=null&&!p.getCategory().isBlank())categories.add(p.getCategory());});categoryFilter.setItems(FXCollections.observableArrayList("All"));categoryFilter.getItems().addAll(categories);categoryFilter.setValue("All");refresh();clearForm();}
private void refresh(){List<Product> items=AppContext.getInstance().products().search(searchField.getText(),categoryFilter.getValue(),lowStockOnly.isSelected());table.setItems(FXCollections.observableArrayList(items));}
private void edit(Product p){selected=p;if(p==null)return;skuField.setText(p.getSku());nameField.setText(p.getName());descriptionField.setText(p.getDescription());categoryField.setText(p.getCategory());minimumField.setText(String.valueOf(p.getMinimumStock()));activeCheck.setSelected(p.isActive());locationCombo.getItems().stream().filter(l->Objects.equals(l.getId(),p.getLocationId())).findFirst().ifPresentOrElse(locationCombo::setValue,()->locationCombo.setValue(null));}
@FXML private void save(){try{Product p=selected==null?new Product():selected;p.setSku(skuField.getText());p.setName(nameField.getText());p.setDescription(descriptionField.getText());p.setCategory(categoryField.getText());p.setMinimumStock(Integer.parseInt(minimumField.getText()));p.setActive(activeCheck.isSelected());p.setLocationId(locationCombo.getValue()==null?null:locationCombo.getValue().getId());if(selected==null)p.setQuantity(0);AppContext.getInstance().products().save(p);AlertUtil.info("Saved","Product saved successfully.");clearForm();refresh();}catch(NumberFormatException e){AlertUtil.error("Invalid value","Minimum stock must be an integer.");}catch(RuntimeException e){AlertUtil.error("Could not save product",e.getMessage());}}
@FXML private void newProduct(){clearForm();table.getSelectionModel().clearSelection();}
@FXML private void deactivate(){if(selected==null){AlertUtil.error("No selection","Select a product first.");return;}if(AlertUtil.confirm("Deactivate product","Deactivate "+selected.getSku()+"?")){AppContext.getInstance().products().deactivate(selected.getId());clearForm();refresh();}}
private void clearForm(){selected=null;skuField.clear();nameField.clear();descriptionField.clear();categoryField.clear();minimumField.setText("0");locationCombo.setValue(null);activeCheck.setSelected(true);}
}
